[package]
authors = ["Vinh Truong <vinhphuc.truong@gmail.com>"]
edition = "2021"
name = "raydiance"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
ash = "0.37.1"
ash-window = "0.12.0"
bytemuck = { version = "1.12.3", features = ["derive"] }
env_logger = "0.10.0"
gltf = "1.0.0"
log = "0.4.17"
nalgebra = { version = "0.31.4", features = ["bytemuck"] }
palette = { version = "0.6.1", features = ["bytemuck"] }
raw-window-handle = "0.5.0"
winit = "0.27.5"

[build-dependencies]
anyhow = "1.0.68"
