[package]
authors = ["Vinh Truong <vinhphuc.truong@gmail.com>"]
edition = "2021"
name = "raydiance"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
approx = "0.5.1"
ash = "0.37.1"
ash-window = "0.12.0"
bytemuck = { version = "1.12.3", features = ["derive"] }
env_logger = "0.10.0"
gltf = "1.0.0"
image = "0.24.5"
imgui = "0.9.0"
imgui-winit-support = "0.9.0"
itertools = "0.10.5"
log = "0.4.17"
nalgebra = { version = "0.31.4", features = ["bytemuck"] }
palette = { version = "0.6.1", features = ["bytemuck"] }
rand = "0.8.5"
rand_pcg = "0.3.1"
raw-window-handle = "0.5.0"
time = { version = "0.3.17", features = ["local-offset", "formatting"] }
winit = "0.27.5"

[build-dependencies]
anyhow = "1.0.68"
