[package]
authors = ["Vinh Truong <vinhphuc.truong@gmail.com>"]
edition = "2021"
name = "raydiance"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
env_logger = "0.10.0"
log = "0.4.17"
winit = "0.27.5"
