[alias]
rr = "run --release"
rr-dbg = "rr debug"
rr-ed = "rr editor"
rr-off-default = "rr offline --render-job-name debug-default --render-config src/assets/cfg/default.render.ron --scene-config src/assets/cfg/debug.scene.ron"
rr-off-preview = "rr offline --render-job-name debug-preview --render-config src/assets/cfg/preview.render.ron --scene-config src/assets/cfg/debug.scene.ron"
rr-off-preview-mat = "rr offline --render-job-name material --render-config src/assets/cfg/preview.render.ron --scene-config src/assets/cfg/material.scene.ron"
rr-off-preview-sky = "rr offline --render-job-name sky --render-config src/assets/cfg/preview.render.ron --scene-config src/assets/cfg/sky.scene.ron"


w-blog = "watch -i docs/blog/index.html -- cargo run blog"
w-off = "watch -- cargo rr -- offline --render-job-name debug-preview --render-config src/assets/cfg/preview.render.ron --scene-config src/assets/cfg/debug.scene.ron"
w-test-all = "watch -- cargo test -- --nocapture"
w-test-exact = "watch -- cargo test -- --nocapture --exact"

[env]
RUST_LOG = "info"
# RAYON_NUM_THREADS = "1"
