# Some of steps are borrowed from https://matklad.github.io/2021/09/04/fast-rust-builds.html

name: ci
on: push
jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --locked

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets -- --nocapture --quiet

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
